import axiomatics_elementary_properties_groups_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace axiomatics_elementary_properties_groups_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end axiomatics_elementary_properties_groups_theorem_canonical_lane_mathlib
end HautevilleHouse
